class Solution:
    def nthSuperUglyNumber(self, n: int, primes: List[int]) -> int:
        
        # dp[i] will store the ith super ugly number
        # We start with dp[0] = 1 because 1 is always included
        dp = [1] * n
        
        # We maintain one pointer for each prime
        # pointers[j] tells which index in dp this prime is currently using
        pointers = [0] * len(primes)
        
        # This array stores current values generated by each prime
        values = list(primes)  # initially primes * dp[0]
        
        # Example (primes = [2,3]):
        # dp = [1, _, _, ...]
        # pointers = [0,0]
        # values = [2,3]
        
        for i in range(1, n):
            
            # Pick the smallest among all generated values
            next_ugly = min(values)
            
            # Add it to dp
            dp[i] = next_ugly
            
            # ---- DRY RUN TRACKING ----
            # Example:
            # dp = [1,2,3,4,6,...]
            # values = [6,6] → min = 6
            
            # Now update all pointers that contributed this value
            for j in range(len(primes)):
                
                if values[j] == next_ugly:
                    
                    # Move pointer forward
                    pointers[j] += 1
                    
                    # Generate next value for this prime
                    # WHY: we move to next dp index to avoid duplicate generation
                    values[j] = primes[j] * dp[pointers[j]]
                    
                    # ---- DRY RUN ----
                    # Suppose:
                    # primes = [2,3]
                    # dp = [1,2,3,4]
                    # pointers = [2,1]
                    # values = [6,6]
                    #
                    # next_ugly = 6
                    # Both match → move both pointers
                    # new values = [2*dp[3], 3*dp[2]] = [8,9]
        
        # Return the nth super ugly number
        return dp[n - 1]